set shell = CreateObject("WScript.Shell")
shell.AppActivate("CONN")

shell.SendKeys "{ENTER}", True
shell.SendKeys "m", True
shell.SendKeys "m", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "{DOWN}", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "m", True
shell.SendKeys "m", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "{DOWN}", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "m", True
shell.SendKeys "m", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "{DOWN}", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "m", True
shell.SendKeys "m", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "{DOWN}", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "m", True
shell.SendKeys "m", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "{DOWN}", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "m", True
shell.SendKeys "m", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "{DOWN}", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "m", True
shell.SendKeys "m", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "{DOWN}", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "m", True
shell.SendKeys "m", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "{DOWN}", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "m", True
shell.SendKeys "m", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "{DOWN}", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "m", True
shell.SendKeys "m", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "{DOWN}", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "m", True
shell.SendKeys "m", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "{DOWN}", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "m", True
shell.SendKeys "m", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "{DOWN}", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "m", True
shell.SendKeys "m", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "{DOWN}", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "m", True
shell.SendKeys "m", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "{DOWN}", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "m", True
shell.SendKeys "m", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "{DOWN}", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "m", True
shell.SendKeys "m", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "{DOWN}", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "m", True
shell.SendKeys "m", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "{DOWN}", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "m", True
shell.SendKeys "m", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "{DOWN}", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "m", True
shell.SendKeys "m", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "{DOWN}", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "m", True
shell.SendKeys "m", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "{DOWN}", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "m", True
shell.SendKeys "m", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "{DOWN}", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "m", True
shell.SendKeys "m", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "{DOWN}", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "m", True
shell.SendKeys "m", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "{DOWN}", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "m", True
shell.SendKeys "m", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "{DOWN}", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "m", True
shell.SendKeys "m", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "{DOWN}", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "m", True
shell.SendKeys "m", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "{DOWN}", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "m", True
shell.SendKeys "m", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "{DOWN}", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "m", True
shell.SendKeys "m", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "{DOWN}", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "m", True
shell.SendKeys "m", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "{DOWN}", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "m", True
shell.SendKeys "m", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "{DOWN}", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "m", True
shell.SendKeys "m", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "{DOWN}", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "m", True
shell.SendKeys "m", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "{DOWN}", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "m", True
shell.SendKeys "m", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "{DOWN}", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "m", True
shell.SendKeys "m", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "{DOWN}", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "m", True
shell.SendKeys "m", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "{DOWN}", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "m", True
shell.SendKeys "m", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "{DOWN}", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "m", True
shell.SendKeys "m", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "{DOWN}", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "m", True
shell.SendKeys "m", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "{DOWN}", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "m", True
shell.SendKeys "m", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "{DOWN}", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "m", True
shell.SendKeys "m", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "{DOWN}", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "m", True
shell.SendKeys "m", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "{DOWN}", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "m", True
shell.SendKeys "m", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "{DOWN}", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "m", True
shell.SendKeys "m", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "{DOWN}", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "m", True
shell.SendKeys "m", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "{DOWN}", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "m", True
shell.SendKeys "m", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "{DOWN}", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "m", True
shell.SendKeys "m", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "{DOWN}", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "m", True
shell.SendKeys "m", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "{DOWN}", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "m", True
shell.SendKeys "m", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "{DOWN}", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "m", True
shell.SendKeys "m", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "{DOWN}", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "m", True
shell.SendKeys "m", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "{DOWN}", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "m", True
shell.SendKeys "m", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "{DOWN}", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "m", True
shell.SendKeys "m", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "{DOWN}", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "m", True
shell.SendKeys "m", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "{DOWN}", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "m", True
shell.SendKeys "m", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "{DOWN}", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "m", True
shell.SendKeys "m", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "{DOWN}", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "m", True
shell.SendKeys "m", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "{DOWN}", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "m", True
shell.SendKeys "m", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "{DOWN}", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "m", True
shell.SendKeys "m", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "{DOWN}", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "m", True
shell.SendKeys "m", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "{DOWN}", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "m", True
shell.SendKeys "m", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "{DOWN}", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "m", True
shell.SendKeys "m", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "{DOWN}", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "m", True
shell.SendKeys "m", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "{DOWN}", True