set shell = CreateObject("WScript.Shell")
shell.AppActivate("R1.xlsx")

shell.SendKeys "{END}", True
shell.SendKeys ".", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "{DOWN}", True
shell.SendKeys "{END}", True
shell.SendKeys ".", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "{DOWN}", True
shell.SendKeys "{END}", True
shell.SendKeys ".", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "{DOWN}", True
shell.SendKeys "{END}", True
shell.SendKeys ".", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "{DOWN}", True
shell.SendKeys "{END}", True
shell.SendKeys ".", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "{DOWN}", True
shell.SendKeys "{END}", True
shell.SendKeys ".", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "{DOWN}", True
shell.SendKeys "{END}", True
shell.SendKeys ".", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "{DOWN}", True
shell.SendKeys "{END}", True
shell.SendKeys ".", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "{DOWN}", True
shell.SendKeys "{END}", True
shell.SendKeys ".", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "{DOWN}", True
shell.SendKeys "{END}", True
shell.SendKeys ".", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "{DOWN}", True
shell.SendKeys "{END}", True
shell.SendKeys ".", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "{DOWN}", True
shell.SendKeys "{END}", True
shell.SendKeys ".", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "{DOWN}", True
shell.SendKeys "{END}", True
shell.SendKeys ".", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "{DOWN}", True
shell.SendKeys "{END}", True
shell.SendKeys ".", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "{DOWN}", True
shell.SendKeys "{END}", True
shell.SendKeys ".", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "{DOWN}", True
shell.SendKeys "{END}", True
shell.SendKeys ".", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "{DOWN}", True
shell.SendKeys "{END}", True
shell.SendKeys ".", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "{DOWN}", True
shell.SendKeys "{END}", True
shell.SendKeys ".", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "{DOWN}", True
shell.SendKeys "{END}", True
shell.SendKeys ".", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "{DOWN}", True
shell.SendKeys "{END}", True
shell.SendKeys ".", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "{DOWN}", True
shell.SendKeys "{END}", True
shell.SendKeys ".", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "{DOWN}", True
shell.SendKeys "{END}", True
shell.SendKeys ".", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "{DOWN}", True
shell.SendKeys "{END}", True
shell.SendKeys ".", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "{DOWN}", True
shell.SendKeys "{END}", True
shell.SendKeys ".", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "{DOWN}", True
shell.SendKeys "{END}", True
shell.SendKeys ".", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "{DOWN}", True
shell.SendKeys "{END}", True
shell.SendKeys ".", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "{DOWN}", True
shell.SendKeys "{END}", True
shell.SendKeys ".", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "{DOWN}", True
shell.SendKeys "{END}", True
shell.SendKeys ".", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "{DOWN}", True
shell.SendKeys "{END}", True
shell.SendKeys ".", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "{DOWN}", True
shell.SendKeys "{END}", True
shell.SendKeys ".", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "{DOWN}", True
shell.SendKeys "{END}", True
shell.SendKeys ".", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "{DOWN}", True
shell.SendKeys "{END}", True
shell.SendKeys ".", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "{DOWN}", True
shell.SendKeys "{END}", True
shell.SendKeys ".", True
shell.SendKeys "{ENTER}", True
shell.SendKeys "{DOWN}", True

